export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          user_id: string;
          email: string;
          role: "HOMEOWNER" | "CONTRACTOR" | "ADMIN";
          first_name: string | null;
          last_name: string | null;
          phone: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          email: string;
          role?: "HOMEOWNER" | "CONTRACTOR" | "ADMIN";
          first_name?: string | null;
          last_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          email?: string;
          role?: "HOMEOWNER" | "CONTRACTOR" | "ADMIN";
          first_name?: string | null;
          last_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      home_assessments: {
        Row: {
          id: string;
          profile_id: string | null;
          zip: string;
          state: string | null;
          county_id: string | null;
          electric_utility_id: string | null;
          gas_utility_id: string | null;
          square_footage: number;
          year_built: number;
          bedrooms: number;
          bathrooms: number | null;
          primary_heating_fuel: string;
          current_hvac_type: string;
          hvac_age: number | null;
          has_gas: boolean;
          electric_panel_amps: number | null;
          roof_orientation: string | null;
          roof_age: number | null;
          annual_kwh: number | null;
          annual_therms: number | null;
          household_income: number | null;
          ami_bracket: string | null;
          has_existing_solar: boolean;
          has_ev: boolean;
          urgency: string | null;
          notes: string | null;
          calc_annual_energy_cost: number | null;
          calc_savings_potential: number | null;
          calc_available_rebates: number | null;
          photo_urls: string[];
          utility_bill_urls: string[];
          intake_v2: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          zip: string;
          state?: string | null;
          county_id?: string | null;
          electric_utility_id?: string | null;
          gas_utility_id?: string | null;
          square_footage: number;
          year_built: number;
          bedrooms: number;
          bathrooms?: number | null;
          primary_heating_fuel: string;
          current_hvac_type: string;
          hvac_age?: number | null;
          has_gas?: boolean;
          electric_panel_amps?: number | null;
          roof_orientation?: string | null;
          roof_age?: number | null;
          annual_kwh?: number | null;
          annual_therms?: number | null;
          household_income?: number | null;
          ami_bracket?: string | null;
          has_existing_solar?: boolean;
          has_ev?: boolean;
          urgency?: string | null;
          notes?: string | null;
          calc_annual_energy_cost?: number | null;
          calc_savings_potential?: number | null;
          calc_available_rebates?: number | null;
          photo_urls?: string[];
          utility_bill_urls?: string[];
          intake_v2?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string | null;
          zip?: string;
          state?: string | null;
          county_id?: string | null;
          electric_utility_id?: string | null;
          gas_utility_id?: string | null;
          square_footage?: number;
          year_built?: number;
          bedrooms?: number;
          bathrooms?: number | null;
          primary_heating_fuel?: string;
          current_hvac_type?: string;
          hvac_age?: number | null;
          has_gas?: boolean;
          electric_panel_amps?: number | null;
          roof_orientation?: string | null;
          roof_age?: number | null;
          annual_kwh?: number | null;
          annual_therms?: number | null;
          household_income?: number | null;
          ami_bracket?: string | null;
          has_existing_solar?: boolean;
          has_ev?: boolean;
          urgency?: string | null;
          notes?: string | null;
          calc_annual_energy_cost?: number | null;
          calc_savings_potential?: number | null;
          calc_available_rebates?: number | null;
          photo_urls?: string[];
          utility_bill_urls?: string[];
          intake_v2?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      contractors: {
        Row: {
          id: string;
          profile_id: string;
          business_name: string;
          tier: "VERIFIED" | "PREFERRED" | "ELITE";
          status: "PENDING_REVIEW" | "ACTIVE" | "SUSPENDED" | "REJECTED";
          categories: string[];
          service_zips: string[];
          service_area_kind: "state" | "counties" | "metro" | null;
          service_area_state_code: string | null;
          service_area_county_ids: string[];
          service_area_metro_id: string | null;
          service_utility_ids: string[];
          bio: string | null;
          website: string | null;
          logo_url: string | null;
          mhic_license: string | null;
          mhic_verified: boolean;
          hvac_license: string | null;
          electrical_license: string | null;
          plumbing_license: string | null;
          wssc_license: string | null;
          certifications: string[];
          mea_participating: boolean;
          insurance_verified: boolean;
          background_check_passed: boolean;
          insurance_expiry: string | null;
          rating: number;
          review_count: number;
          completed_projects: number;
          stripe_customer_id: string | null;
          subscription_id: string | null;
          subscription_tier: string | null;
          subscription_status: string | null;
          subscription_end_date: string | null;
          lead_credits: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          business_name: string;
          tier?: "VERIFIED" | "PREFERRED" | "ELITE";
          status?: "PENDING_REVIEW" | "ACTIVE" | "SUSPENDED" | "REJECTED";
          categories?: string[];
          service_zips?: string[];
          service_area_kind?: "state" | "counties" | "metro" | null;
          service_area_state_code?: string | null;
          service_area_county_ids?: string[];
          service_area_metro_id?: string | null;
          service_utility_ids?: string[];
          bio?: string | null;
          website?: string | null;
          logo_url?: string | null;
          mhic_license?: string | null;
          mhic_verified?: boolean;
          hvac_license?: string | null;
          electrical_license?: string | null;
          plumbing_license?: string | null;
          wssc_license?: string | null;
          certifications?: string[];
          mea_participating?: boolean;
          insurance_verified?: boolean;
          background_check_passed?: boolean;
          insurance_expiry?: string | null;
          rating?: number;
          review_count?: number;
          completed_projects?: number;
          stripe_customer_id?: string | null;
          subscription_id?: string | null;
          subscription_tier?: string | null;
          subscription_status?: string | null;
          subscription_end_date?: string | null;
          lead_credits?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          business_name?: string;
          tier?: "VERIFIED" | "PREFERRED" | "ELITE";
          status?: "PENDING_REVIEW" | "ACTIVE" | "SUSPENDED" | "REJECTED";
          categories?: string[];
          service_zips?: string[];
          service_area_kind?: "state" | "counties" | "metro" | null;
          service_area_state_code?: string | null;
          service_area_county_ids?: string[];
          service_area_metro_id?: string | null;
          service_utility_ids?: string[];
          bio?: string | null;
          website?: string | null;
          logo_url?: string | null;
          mhic_license?: string | null;
          mhic_verified?: boolean;
          hvac_license?: string | null;
          electrical_license?: string | null;
          plumbing_license?: string | null;
          wssc_license?: string | null;
          certifications?: string[];
          mea_participating?: boolean;
          insurance_verified?: boolean;
          background_check_passed?: boolean;
          insurance_expiry?: string | null;
          rating?: number;
          review_count?: number;
          completed_projects?: number;
          stripe_customer_id?: string | null;
          subscription_id?: string | null;
          subscription_tier?: string | null;
          subscription_status?: string | null;
          subscription_end_date?: string | null;
          lead_credits?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          assessment_id: string;
          contractor_id: string;
          status: "NEW" | "CONTACTED" | "QUOTED" | "WON" | "LOST" | "DISPUTED";
          price_paid: number;
          stripe_payment_id: string | null;
          contacted_at: string | null;
          quoted_at: string | null;
          closed_at: string | null;
          closed_value: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          assessment_id: string;
          contractor_id: string;
          status?: "NEW" | "CONTACTED" | "QUOTED" | "WON" | "LOST" | "DISPUTED";
          price_paid: number;
          stripe_payment_id?: string | null;
          contacted_at?: string | null;
          quoted_at?: string | null;
          closed_at?: string | null;
          closed_value?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          assessment_id?: string;
          contractor_id?: string;
          status?: "NEW" | "CONTACTED" | "QUOTED" | "WON" | "LOST" | "DISPUTED";
          price_paid?: number;
          stripe_payment_id?: string | null;
          contacted_at?: string | null;
          quoted_at?: string | null;
          closed_at?: string | null;
          closed_value?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      stripe_events: {
        Row: {
          id: string;
          type: string;
          data: Json;
          created_at: string;
        };
        Insert: {
          id: string;
          type: string;
          data: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          type?: string;
          data?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
