import type { CommercialIncentive } from "./feature-types";

export const COMMERCIAL_INCENTIVES: CommercialIncentive[] = [
  {
    id: "pepco-commercial-custom",
    region: "MD",
    provider: "Pepco",
    programName: "Commercial custom incentives",
    measureTypes: ["controls", "retro-commissioning", "VFD", "HVAC optimization"],
    incentiveType: "custom",
    estimatedRange: "Custom range; verify before proposal",
    requiredDocs: ["Scope of work", "Baseline trend evidence", "Estimated savings", "Final invoice"],
    sourceUrl: "https://www.pepco.com/ways-to-save/for-your-business",
    lastVerified: "2026-04-27",
    notes: "Use for controls/FDD-backed measures where prescriptive rebates do not fit.",
  },
  {
    id: "bge-commercial-programs",
    region: "MD",
    provider: "BGE",
    programName: "Commercial energy efficiency programs",
    measureTypes: ["lighting", "HVAC", "controls", "custom"],
    incentiveType: "custom",
    estimatedRange: "Varies by measure and verified savings",
    requiredDocs: ["Utility account", "Pre-install application where required", "Equipment specs", "Invoice"],
    sourceUrl: "https://bgesmartenergy.com/business",
    lastVerified: "2026-04-27",
    notes: "Placeholder for buildings outside Pepco territory; verify eligibility by account.",
  },
  {
    id: "dcseu-custom",
    region: "DC",
    provider: "DCSEU",
    programName: "DCSEU business incentives",
    measureTypes: ["retro-commissioning", "controls", "HVAC", "custom"],
    incentiveType: "custom",
    estimatedRange: "Varies; pre-approval commonly required",
    requiredDocs: ["DC service address", "Project scope", "Savings estimate", "Contractor invoice"],
    sourceUrl: "https://www.dcseu.com/for-my-business",
    lastVerified: "2026-04-27",
    notes: "Use for DC buildings; flag pre-approval before installation.",
  },
  {
    id: "washington-gas-commercial",
    region: "MD",
    provider: "Washington Gas",
    programName: "Commercial gas efficiency programs",
    measureTypes: ["boiler", "controls", "heating optimization", "custom gas"],
    incentiveType: "prescriptive",
    estimatedRange: "Program-dependent range",
    requiredDocs: ["Gas account", "Equipment specs", "Combustion/heating scope", "Invoice"],
    sourceUrl: "https://washingtongas.com",
    lastVerified: "2026-04-27",
    notes: "Match to boiler lockout, heating controls, and gas-side opportunities.",
  },
  {
    id: "mc-green-bank-financing",
    region: "MD",
    provider: "Montgomery County Green Bank",
    programName: "Commercial clean energy financing",
    measureTypes: ["financing", "HVAC", "solar", "controls", "building upgrades"],
    incentiveType: "financing",
    estimatedRange: "Financing, not a rebate",
    requiredDocs: ["Project budget", "Building ownership", "Energy savings estimate", "Contractor proposal"],
    sourceUrl: "https://mcgreenbank.org",
    lastVerified: "2026-04-27",
    notes: "Useful for no-upfront-cost or cash-flow-positive pilots.",
  },
  {
    id: "mea-commercial-grants",
    region: "MD",
    provider: "Maryland Energy Administration",
    programName: "Commercial / public-sector grant flags",
    measureTypes: ["public sector", "nonprofit", "schools", "resilience", "energy efficiency"],
    incentiveType: "grant",
    estimatedRange: "Verify current fiscal-year program",
    requiredDocs: ["Applicant type", "Scope", "Budget", "Savings estimate", "Funding timeline"],
    sourceUrl: "https://energy.maryland.gov",
    lastVerified: "2026-04-27",
    notes: "Use as a prompt to verify active FY programs before including exact amounts.",
  },
  {
    id: "demand-response",
    region: "National",
    provider: "Utility / grid aggregator",
    programName: "Demand response enrollment",
    measureTypes: ["demand response", "load shed", "controls"],
    incentiveType: "demand_response",
    estimatedRange: "Depends on enrolled kW and event performance",
    requiredDocs: ["Interval demand data", "Shed plan", "Operational constraints", "Contact for curtailment"],
    lastVerified: "2026-04-27",
    notes: "Match to R020 and peak-demand opportunities; never automate without approval.",
  },
];

export function incentivesForMeasure(measure: string): CommercialIncentive[] {
  const normalized = measure.toLowerCase();
  return COMMERCIAL_INCENTIVES.filter((incentive) =>
    incentive.measureTypes.some((type) => normalized.includes(type.toLowerCase())),
  );
}
