import type { FddRuleDefinition } from "./feature-types";

export const COMMERCIAL_RULE_DEFINITIONS: FddRuleDefinition[] = [
  {
    id: "R001",
    title: "Simultaneous heating and cooling",
    defaultSeverity: "high",
    requiredPoints: ["cooling_valve_cmd", "heating_valve_cmd"],
    explanation: "Heating and cooling commands overlap on the same air stream or zone.",
    detectionLogic: "Flag when both valves are above 10% for at least 15 minutes in the same window.",
    savingsPlaceholder: "Estimate reheat/cooling overlap by valve position, airflow proxy, and runtime hours.",
    recommendedActions: ["Check sequencing", "Verify deadband", "Inspect leaking valves"],
    module: "airside",
  },
  {
    id: "R002",
    title: "Economizer not economizing",
    defaultSeverity: "high",
    requiredPoints: ["outside_air_temp", "mixed_air_temp", "oa_damper_cmd"],
    explanation: "The building uses mechanical cooling when outdoor air could provide free cooling.",
    detectionLogic: "Flag free-cooling hours where OA damper remains at minimum and cooling remains active.",
    savingsPlaceholder: "Estimate avoided compressor/chiller runtime across shoulder-season hours.",
    recommendedActions: ["Inspect damper actuator", "Verify economizer enable setpoints", "Trend MAT/OAT after repair"],
    module: "airside",
  },
  {
    id: "R003",
    title: "Low delta-T on chilled water",
    defaultSeverity: "medium",
    requiredPoints: ["chw_supply_temp", "chw_return_temp"],
    explanation: "Low chilled-water temperature differential points to bypass flow or poor coil performance.",
    detectionLogic: "Flag sustained CHW delta-T below 6F during cooling operation.",
    savingsPlaceholder: "Estimate pump penalty and chiller efficiency loss using plant runtime.",
    recommendedActions: ["Check bypass valves", "Inspect coils", "Review pump differential pressure control"],
    module: "hydronic",
  },
  {
    id: "R004",
    title: "Overventilation during unoccupied hours",
    defaultSeverity: "high",
    requiredPoints: ["fan_status", "occupancy_status", "operating_hours"],
    explanation: "Outdoor air and fans run when the building is scheduled to be empty.",
    detectionLogic: "Flag fan runtime outside scheduled occupied windows without an override reason.",
    savingsPlaceholder: "Estimate fan energy plus heating/cooling outdoor-air tempering load.",
    recommendedActions: ["Tighten schedules", "Confirm override workflow", "Verify minimum ventilation stays code-compliant"],
    module: "occupancy",
  },
  {
    id: "R005",
    title: "Hot deck / cold deck fighting",
    defaultSeverity: "medium",
    requiredPoints: ["supply_air_temp", "sat_sp"],
    explanation: "Supply air temperature oscillates around setpoint, causing reheat and comfort instability.",
    detectionLogic: "Flag repeated SAT swings greater than 4F around setpoint within one hour.",
    savingsPlaceholder: "Estimate excess reheat/cooling cycles and comfort-driven override risk.",
    recommendedActions: ["Tune PID loops", "Review reset range", "Inspect stuck dampers or valves"],
    module: "controls",
  },
  {
    id: "R006",
    title: "Zone setpoint drift",
    defaultSeverity: "low",
    requiredPoints: ["zone_temp", "zone_cooling_sp", "zone_heating_sp"],
    explanation: "Zones spend too much occupied time outside comfort deadband.",
    detectionLogic: "Flag zones outside deadband for more than 25% of occupied hours.",
    savingsPlaceholder: "Estimate comfort-driven runtime and work-order risk; savings vary by root cause.",
    recommendedActions: ["Review setpoint policy", "Check sensor placement", "Balance airflow"],
    module: "controls",
  },
  {
    id: "R007",
    title: "After-hours runtime",
    defaultSeverity: "medium",
    requiredPoints: ["fan_status", "operating_hours", "operating_calendar"],
    explanation: "Equipment runs outside the approved schedule.",
    detectionLogic: "Flag weekday/weekend fan or pump runtime outside calendar windows.",
    savingsPlaceholder: "Multiply after-hours runtime by effective blended rate and load proxy.",
    recommendedActions: ["Fix schedules", "Add holiday calendar", "Review tenant override billing"],
    module: "occupancy",
  },
  {
    id: "R008",
    title: "Short-cycling fans",
    defaultSeverity: "medium",
    requiredPoints: ["fan_status"],
    explanation: "Fans switch on/off too frequently, wasting energy and wearing equipment.",
    detectionLogic: "Flag six or more fan status transitions per hour for sustained periods.",
    savingsPlaceholder: "Estimate avoidable starts and motor/VFD wear rather than guaranteed energy savings.",
    recommendedActions: ["Review minimum on/off timers", "Check pressure reset", "Inspect VFD fault history"],
    module: "controls",
  },
  {
    id: "R009",
    title: "Reheat without cooling lockout",
    defaultSeverity: "high",
    requiredPoints: ["heating_valve_cmd", "supply_air_temp", "outside_air_temp"],
    explanation: "Terminal reheat runs while supply air is unnecessarily cold.",
    detectionLogic: "Flag reheat active while SAT is below 60F and upstream cooling is not needed.",
    savingsPlaceholder: "Estimate terminal reheat penalty during low-load hours.",
    recommendedActions: ["Add cooling lockout", "Raise SAT reset floor", "Check VAV minimum airflow"],
    module: "airside",
  },
  {
    id: "R010",
    title: "Static pressure reset disabled",
    defaultSeverity: "medium",
    requiredPoints: ["supply_air_pressure", "sap_sp", "vfd_speed_cmd"],
    explanation: "Supply fans maintain a fixed pressure even when load is low.",
    detectionLogic: "Flag flat SAP setpoint across varying fan speed/load conditions.",
    savingsPlaceholder: "Estimate fan cube-law savings from trim-and-respond reset.",
    recommendedActions: ["Enable static pressure reset", "Confirm critical-zone logic", "Verify no comfort complaints"],
    module: "airside",
  },
  {
    id: "R011",
    title: "Filter pressure drop abnormal / MESP opportunity",
    defaultSeverity: "medium",
    requiredPoints: ["filter_dp", "fan_speed"],
    explanation: "Filter pressure drop is high or unstable, suggesting maintenance or filtration optimization.",
    detectionLogic: "Flag filter DP above expected threshold after normalizing for fan speed.",
    savingsPlaceholder: "Estimate fan penalty and maintenance urgency; validate against IAQ requirements.",
    recommendedActions: ["Inspect filters", "Review MERV/MESP options", "Confirm IAQ guardrails"],
    module: "iaq",
  },
  {
    id: "R012",
    title: "Supply air temperature reset disabled",
    defaultSeverity: "medium",
    requiredPoints: ["supply_air_temp", "sat_sp", "outside_air_temp"],
    explanation: "SAT setpoint stays fixed instead of floating with load or outdoor conditions.",
    detectionLogic: "Flag flat SAT setpoint across wide outdoor air and load conditions.",
    savingsPlaceholder: "Estimate avoided reheat/cooling from reset strategy simulation.",
    recommendedActions: ["Enable SAT reset", "Set comfort limits", "Trend reheat calls after change"],
    module: "controls",
  },
  {
    id: "R013",
    title: "Chiller short cycling",
    defaultSeverity: "high",
    requiredPoints: ["chiller_status", "chw_supply_temp"],
    explanation: "Chiller starts/stops too frequently, reducing efficiency and equipment life.",
    detectionLogic: "Flag repeated chiller cycles below minimum runtime thresholds.",
    savingsPlaceholder: "Estimate cycling losses and avoided maintenance risk.",
    recommendedActions: ["Review staging", "Check minimum load", "Inspect buffer tank or bypass behavior"],
    module: "hydronic",
  },
  {
    id: "R014",
    title: "Boiler lockout failure during warm weather",
    defaultSeverity: "high",
    requiredPoints: ["boiler_status", "outside_air_temp"],
    explanation: "Boilers run when outdoor conditions should lock them out.",
    detectionLogic: "Flag boiler runtime above warm-weather lockout temperature.",
    savingsPlaceholder: "Estimate therm waste during warm-weather runtime windows.",
    recommendedActions: ["Enable boiler lockout", "Check DHW separation", "Verify freeze protection constraints"],
    module: "hydronic",
  },
  {
    id: "R015",
    title: "Excess outdoor air during peak heating/cooling",
    defaultSeverity: "high",
    requiredPoints: ["oa_damper_cmd", "outside_air_temp", "fan_status"],
    explanation: "Outdoor air exceeds minimum needs during peak load periods.",
    detectionLogic: "Flag OA damper above minimum during extreme weather without occupancy/IAQ justification.",
    savingsPlaceholder: "Estimate outdoor-air tempering load while preserving code minimum ventilation.",
    recommendedActions: ["Calibrate dampers", "Review minimum OA", "Confirm CO2/IAQ limits before changes"],
    module: "iaq",
  },
  {
    id: "R016",
    title: "VFD fan speed pinned high",
    defaultSeverity: "high",
    requiredPoints: ["fan_speed", "static_pressure", "vav_damper_positions"],
    explanation: "Fan speed remains high even when downstream demand is low.",
    detectionLogic: "Flag fan speed above 85% while most VAV dampers are below 60%.",
    savingsPlaceholder: "Estimate fan energy savings using cube-law approximation.",
    recommendedActions: ["Review pressure reset", "Find rogue zones", "Check VFD control mode"],
    module: "airside",
  },
  {
    id: "R017",
    title: "Rogue zone driving AHU",
    defaultSeverity: "medium",
    requiredPoints: ["zone_temp", "vav_damper_position", "ahu_mode"],
    explanation: "One or two zones drive an entire air handler into inefficient operation.",
    detectionLogic: "Flag isolated zones with persistent calls while peer zones are satisfied.",
    savingsPlaceholder: "Estimate system-level runtime caused by local zone issue.",
    recommendedActions: ["Inspect zone sensor", "Check damper actuator", "Rebalance local airflow"],
    module: "controls",
  },
  {
    id: "R018",
    title: "Occupancy schedule mismatch",
    defaultSeverity: "medium",
    requiredPoints: ["occupancy_count", "operating_schedule", "fan_status"],
    explanation: "HVAC schedule does not match actual use patterns.",
    detectionLogic: "Flag occupied HVAC runtime with low/no occupancy or occupancy without adequate conditioning.",
    savingsPlaceholder: "Estimate savings from schedule alignment and exception handling.",
    recommendedActions: ["Update schedules", "Add exception calendar", "Consider occupancy-driven pilot planning"],
    module: "occupancy",
  },
  {
    id: "R019",
    title: "Sensor calibration drift",
    defaultSeverity: "low",
    requiredPoints: ["zone_temp", "peer_zone_temp", "outside_air_temp"],
    explanation: "One sensor diverges from peer sensors or expected ranges.",
    detectionLogic: "Flag persistent offset from peer median after normalizing by zone type.",
    savingsPlaceholder: "Estimate avoided comfort/runtime penalties after recalibration.",
    recommendedActions: ["Field-calibrate sensor", "Check placement", "Replace failed sensor if drift persists"],
    module: "controls",
  },
  {
    id: "R020",
    title: "Demand response shed opportunity",
    defaultSeverity: "medium",
    requiredPoints: ["interval_kw", "equipment_status", "operating_schedule"],
    explanation: "Flexible loads could be staged or pre-cooled during peak events.",
    detectionLogic: "Flag repeatable peak windows with noncritical controllable load.",
    savingsPlaceholder: "Estimate demand charge savings and DR enrollment value; verify comfort constraints.",
    recommendedActions: ["Identify shed sequence", "Define manual override", "Validate with utility DR program"],
    module: "demand",
  },
];

export function getCommercialRule(id: string) {
  return COMMERCIAL_RULE_DEFINITIONS.find((rule) => rule.id === id);
}
