import type { FddFinding } from "./feature-types";

export const SAMPLE_FDD_FINDINGS: FddFinding[] = [
  {
    id: "finding-afterhours-runtime",
    ruleId: "R007",
    title: "AHU-2 runs 42 hrs/week after occupancy",
    severity: "high",
    confidence: 88,
    annualWasteDollarsLow: 5200,
    annualWasteDollarsBase: 8200,
    annualWasteDollarsHigh: 11800,
    annualKwhWaste: 58500,
    co2eTons: 11.5,
    affectedEquipment: ["AHU-2", "Supply fan VFD"],
    affectedZones: ["East classrooms"],
    evidenceWindows: [
      {
        start: "2026-04-15T18:00:00-04:00",
        end: "2026-04-16T06:00:00-04:00",
        points: ["ahu2_fan", "ahu2_oat", "school_calendar"],
        observed: "Fan remained enabled through an unoccupied overnight window.",
      },
    ],
    likelyCauses: ["Holiday calendar missing", "Temporary override left active", "BAS schedule drift"],
    recommendedActions: ["Tighten AHU-2 schedule", "Add school holiday calendar", "Trend one week after schedule update"],
    requiredData: ["fan_status", "operating_hours", "operating_calendar"],
    missingData: ["activity schedule export"],
    rebateMatches: ["pepco-commercial-custom", "demand-response"],
    verificationPlan: "Compare normalized after-hours fan runtime for two weeks before and after schedule correction.",
  },
  {
    id: "finding-static-pressure-reset",
    ruleId: "R010",
    title: "Static pressure reset disabled on VAV system",
    severity: "medium",
    confidence: 81,
    annualWasteDollarsLow: 3600,
    annualWasteDollarsBase: 6100,
    annualWasteDollarsHigh: 9400,
    annualKwhWaste: 43600,
    co2eTons: 8.6,
    affectedEquipment: ["AHU-2", "VAV boxes"],
    affectedZones: ["East classrooms", "Media center"],
    evidenceWindows: [
      {
        start: "2026-04-18T08:00:00-04:00",
        end: "2026-04-18T15:00:00-04:00",
        points: ["ahu2_sap", "ahu2_vfd", "vav_damper_positions"],
        observed: "Supply air pressure setpoint stayed flat while fan speed remained high.",
      },
    ],
    likelyCauses: ["Trim-and-respond disabled", "Critical zone not configured", "Pressure sensor offset"],
    recommendedActions: ["Enable static pressure reset", "Confirm critical-zone logic", "Validate no comfort complaints"],
    requiredData: ["supply_air_pressure", "sap_sp", "vfd_speed_cmd"],
    missingData: ["VAV damper position export"],
    rebateMatches: ["pepco-commercial-custom"],
    verificationPlan: "Track fan speed, pressure setpoint, and comfort complaints before/after reset enablement.",
  },
  {
    id: "finding-floor-utilization",
    ruleId: "R018",
    title: "Floor 3 averages 38% utilization while ventilation assumes 100%",
    severity: "medium",
    confidence: 72,
    annualWasteDollarsLow: 4400,
    annualWasteDollarsBase: 7600,
    annualWasteDollarsHigh: 12400,
    annualKwhWaste: 39000,
    co2eTons: 7.7,
    affectedEquipment: ["AHU-3", "OA damper"],
    affectedZones: ["Floor 3 offices", "Conference wing"],
    evidenceWindows: [
      {
        start: "2026-04-08T09:00:00-04:00",
        end: "2026-04-12T17:00:00-04:00",
        points: ["occupancy_count", "ahu3_oa_damper", "co2_floor3"],
        observed: "Occupancy stayed below 45% while minimum OA schedule remained at full occupied mode.",
      },
    ],
    likelyCauses: ["Hybrid schedule not reflected in BAS", "No occupancy-driven ventilation sequence"],
    recommendedActions: ["Design O-DCV pilot plan", "Set IAQ guardrails", "Start with manual schedule adjustment"],
    requiredData: ["occupancy_count", "operating_schedule", "fan_status"],
    missingData: ["Room-level occupancy history"],
    rebateMatches: ["pepco-commercial-custom", "mc-green-bank-financing"],
    verificationPlan: "Verify CO2 remains below guardrails while reducing unoccupied airflow in pilot zones.",
  },
];
