import type { CommercialAssessment, FloorplanZone } from "./feature-types";

export const SAMPLE_COMMERCIAL_ASSESSMENT: CommercialAssessment = {
  id: "assessment-sample-school",
  buildingName: "Sample Middle School",
  address: "1200 Campus Drive, Rockville, MD 20850",
  buildingType: "school",
  sqft: 65000,
  yearBuilt: 1998,
  lastRenovationYear: 2017,
  utilityProvider: "Pepco",
  annualElectricSpend: 148000,
  annualGasSpend: 43000,
  annualKwh: 982000,
  annualTherms: 19800,
  basVendor: "Niagara",
  hasVfds: true,
  hasCentralAhus: true,
  hasCo2Sensors: true,
  hasIaqSensors: false,
  hasSubmeters: false,
  hasControllableOaDampers: true,
  basSupportsSchedules: true,
  variableOccupancy: true,
  floorplanZonesMapped: true,
  iaqConstraintsKnown: true,
  comfortComplaints: true,
  occupancyPattern: "seasonal",
  operatingSchedule: "School days 7:00 AM - 5:00 PM; activities vary after-hours",
  uploadedData: {
    utilityBills: true,
    intervalData: true,
    bmsTrendCsv: true,
    pointList: true,
    floorplan: true,
    equipmentSchedule: false,
    occupancyData: true,
    iaqData: false,
  },
};

export const SAMPLE_PORTFOLIO: CommercialAssessment[] = [
  SAMPLE_COMMERCIAL_ASSESSMENT,
  {
    id: "assessment-office-rockville",
    buildingName: "Rockville Metro Office",
    address: "1550 Research Blvd, Rockville, MD",
    buildingType: "office",
    sqft: 118000,
    yearBuilt: 2006,
    utilityProvider: "Pepco",
    annualElectricSpend: 286000,
    annualGasSpend: 62000,
    annualKwh: 1720000,
    basVendor: "Metasys",
    hasVfds: true,
    hasCentralAhus: true,
    hasCo2Sensors: false,
    hasIaqSensors: false,
    hasSubmeters: true,
    hasControllableOaDampers: true,
    basSupportsSchedules: true,
    variableOccupancy: true,
    floorplanZonesMapped: false,
    occupancyPattern: "hybrid",
    uploadedData: {
      utilityBills: true,
      intervalData: true,
      bmsTrendCsv: true,
      pointList: true,
      floorplan: false,
      equipmentSchedule: true,
      occupancyData: false,
      iaqData: false,
    },
  },
  {
    id: "assessment-nonprofit-dc",
    buildingName: "Dupont Nonprofit Center",
    address: "1700 Connecticut Ave NW, Washington, DC",
    buildingType: "nonprofit",
    sqft: 42000,
    yearBuilt: 1972,
    utilityProvider: "Pepco DC",
    annualElectricSpend: 92000,
    annualGasSpend: 26000,
    annualKwh: 510000,
    basVendor: "Unknown",
    hasVfds: false,
    hasCentralAhus: true,
    hasCo2Sensors: false,
    hasIaqSensors: false,
    hasSubmeters: false,
    hasControllableOaDampers: false,
    basSupportsSchedules: false,
    variableOccupancy: false,
    floorplanZonesMapped: false,
    occupancyPattern: "stable",
    uploadedData: {
      utilityBills: true,
      intervalData: false,
      bmsTrendCsv: false,
      pointList: false,
      floorplan: false,
      equipmentSchedule: false,
      occupancyData: false,
      iaqData: false,
    },
  },
  {
    id: "assessment-gym-bethesda",
    buildingName: "Bethesda Athletic Club",
    address: "7600 Old Georgetown Rd, Bethesda, MD",
    buildingType: "gym",
    sqft: 74000,
    yearBuilt: 2012,
    utilityProvider: "Pepco",
    annualElectricSpend: 244000,
    annualGasSpend: 78000,
    annualKwh: 1390000,
    basVendor: "WebCTRL",
    hasVfds: true,
    hasCentralAhus: true,
    hasCo2Sensors: true,
    hasIaqSensors: true,
    hasSubmeters: false,
    hasControllableOaDampers: true,
    basSupportsSchedules: true,
    variableOccupancy: true,
    floorplanZonesMapped: false,
    occupancyPattern: "seasonal",
    uploadedData: {
      utilityBills: true,
      intervalData: true,
      bmsTrendCsv: true,
      pointList: false,
      floorplan: true,
      equipmentSchedule: false,
      occupancyData: true,
      iaqData: true,
    },
  },
];

export const SAMPLE_FLOORPLAN_ZONES: FloorplanZone[] = [
  {
    id: "zone-classrooms-east",
    name: "East classrooms",
    floor: "2",
    polygon: [
      { x: 8, y: 10 },
      { x: 48, y: 10 },
      { x: 48, y: 44 },
      { x: 8, y: 44 },
    ],
    sqft: 16400,
    useType: "classroom",
    servedByEquipment: ["AHU-2", "VAV-2A", "VAV-2B"],
    occupancySchedule: "School days 7 AM - 3:30 PM",
    occupancyConfidence: 82,
    fddFindingIds: ["finding-afterhours-runtime", "finding-static-pressure-reset"],
    savingsOpportunity: 7200,
  },
  {
    id: "zone-gym",
    name: "Gym and cafeteria",
    floor: "1",
    polygon: [
      { x: 55, y: 12 },
      { x: 92, y: 12 },
      { x: 92, y: 52 },
      { x: 55, y: 52 },
    ],
    sqft: 13800,
    useType: "gym",
    servedByEquipment: ["AHU-1"],
    occupancySchedule: "School day plus evening activities",
    occupancyConfidence: 64,
    fddFindingIds: ["finding-economizer"],
    savingsOpportunity: 5100,
  },
  {
    id: "zone-admin",
    name: "Admin suite",
    floor: "1",
    polygon: [
      { x: 12, y: 58 },
      { x: 38, y: 58 },
      { x: 38, y: 84 },
      { x: 12, y: 84 },
    ],
    sqft: 6900,
    useType: "office",
    servedByEquipment: ["RTU-3"],
    occupancySchedule: "Weekdays 7 AM - 5 PM",
    occupancyConfidence: 74,
    fddFindingIds: ["finding-simultaneous-heat-cool"],
    savingsOpportunity: 3100,
  },
];
